### ISSUE TITLE
Broken Link to StatMod 2nd Edition Exercises

### ISSUE THREAD

**Issue by homerhanumat** [ProjectMOSAIC/mosaic-web#1]
At the end of each chapter, the 2nd Edition of Statistical Modeling refers to exercises at:

>[http://www.mosaic-web.org/StatisticalModeling/Exercises](http://www.mosaic-web.org/StatisticalModeling/Exercises)

The link is broken, and I am unable to find any such resources on the current site.  Are the exercises still available and if so can they be added?

**Comment by dtkaplan** [comment]
Yes, the exercises are still available. What was missing was the link, which is now added to the ProjectMOSAIC.github.io site. Sorry it took so long to respond.

**Comment by homerhanumat** [comment]
Thanks!
